version: "3"

services:
  tenda-arm:
    platform: linux/arm/v7
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: tenda-arm
    privileged: true
    networks:
      firmware_net:
        ipv4_address: 192.168.2.2
    ports:
      - "8080:80"

  # attacker:
  #   image: alpine:latest
  #   container_name: tenda-attacker
  #   networks:
  #     firmware_net:
  #       ipv4_address: 192.168.2.100
  #   command: sh -c "apk add --no-cache curl && sleep infinity"
  #   stdin_open: true
  #   tty: true

networks:
  firmware_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.2.0/24
