# version: "3.8"

# networks:
#   iot_bridge:
#     driver: bridge
#     ipam:
#       driver: default
#       config:
#         # 可根据实际网络环境调整网段
#         # 当前环境: 118.202.10.x/24 -> 使用 118.202.11.x/24
#         # 演示环境: 192.168.100.x/24 -> 使用 192.168.101.x/24  
#         # 演示环境: 10.10.2.x/24 -> 使用 10.10.3.x/24
#         - subnet: 10.10.10.0/24
#           # gateway: 10.10.10.254

# services:
#   system-emu:
#     container_name: test1
#     build:
#       context: .
#       dockerfile: ./system-emu/Dockerfile
#     networks:
#       iot_bridge:
#         ipv4_address: 10.10.10.168  # 容器固定IP
#     privileged: true
#     # 不再需要端口映射，直接通过IP访问


version: "3.8"

networks:
  iot_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.10.10.0/24
          gateway: 10.10.10.1

services:
  system-emu:
    container_name: test1
    build:
      context: .
      dockerfile: ./system-emu/Dockerfile
    networks:
      iot_net:
        ipv4_address: 10.10.10.168
    privileged: true